export const LAUNCHES = [
    {
      id: "launch-1",
      name: "RAVEN",
      ticker: "RVN",
      launchpadId: "CCHUVB7C4VB4QT7XCFOQFAJI4GTJNZTZE37GQY5H3UK53EYISSEVWUKH",
      tokenId: "CAKYJF4FRQMF3VS43THFNXB3RWCOHOXUEQE6JRCTEBRRLBD2I5CR23PB",
      softCap: 1000,
      liquidity: 62.5,
      offered: "1900000 RVN",
      icon: "https://api.dicebear.com/7.x/thumbs/svg?seed=RAVEN&backgroundColor=1a1a2e&shapeColor=7c3aed",
    },
    {
      id: "launch-2",
      name: "NORMIES",
      ticker: "NORM",
      launchpadId: "CDWEL3QFJ52UNTZFQVM3O424VYC63STQPI7OIMNQ6G2DA5CCFJM5X4JT",
      tokenId: "CACCNZESK5YAQYYN5NLZLBEJNNPTTNN3H5YK6ICWXEL65UVLGVHNP534",
      softCap: 50000,
      liquidity: 62.5,
      offered: "1900000 NORM",
      icon: "https://api.dicebear.com/7.x/pixel-art/svg?seed=NORMIES&backgroundColor=1a1a2e&clothing=variant01&accessories=variant01",
    },
    {
      id: "launch-3",
      name: "CHIPS",
      ticker: "CHIPS",
      launchpadId: "",
      tokenId: "",
      softCap: 1000,
      liquidity: 62.5,
      offered: "1900000 CHIPS",
      icon: "https://emojicdn.elk.sh/🍟?style=twitter",
    },
    {
      id: "launch-4",
      name: "GOAT",
      ticker: "GOAT",
      launchpadId: "",
      tokenId: "",
      softCap: 5000,
      liquidity: 62.5,
      offered: "1900000 GOAT",
      icon: "https://emojicdn.elk.sh/🐐?style=twitter",
    },
    {
      id: "launch-5",
      name: "PEPE",
      ticker: "PEPE",
      launchpadId: "",
      tokenId: "",
      softCap: 2000,
      liquidity: 62.5,
      offered: "1900000 PEPE",
      icon: "https://emojicdn.elk.sh/🐸?style=twitter",
    },
    {
      id: "launch-6",
      name: "ROCKET",
      ticker: "RKT",
      launchpadId: "",
      tokenId: "",
      softCap: 10000,
      liquidity: 62.5,
      offered: "1900000 RKT",
      icon: "https://emojicdn.elk.sh/🚀?style=twitter",
    },
  ];